### ISSUE TITLE
PHP Warning in newest Wordpress + PHP8.1

### ISSUE THREAD

**Issue by spointecker** [gumlet/wordpress-plugin#5]
hey I saw that with the newest wordpress 5.9.0 and php 8.1 a warning occurs:

maybe you can fix it:

`PHP Warning:  Undefined property: stdClass::$html in /application/web/blog/wp-content/plugins/gumlet/includes/class-gumlet.php on line 328"`

**Comment by adityapatadia** [comment]
`1.2.7` fixes this.
